version: "1"

volumes: 
  employeerole_service: 
    name: volume_name 

services:
  employeedb:
    image: postgres
    restart: unless-stopped
    container_name: employeedb
    environment:
    - POSTGRES_DB=employeedb
    - POSTGRES_HOST_AUTH_METHOD = trust
    - POSTGRES_PASSWORD=backend
    - POSTGRES_USER=backend 
    ports:
      - 5434:5432
    volumes:
      -  employeerole_service:/var/lib/postgresql/data
  backend:
    build:
      context: ../employeedb     
      dockerfile: Dockerfile  
    ports:
      - 8008:8008
    environment:
     SPRING_APPLICATION_JSON: '{ 
        "spring.datasource.url"  : "jdbc:postgresql://host.docker.internal:5434/postgres",
        "spring.datasource.username" : "backend",
        "spring.datasource.password" : "backend",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.PostgreSQLDialect",
        "spring.jpa.hibernate.ddl-auto" : "create"
        
  
         }'  
    depends_on:
      - employeedb 
