server:
    ssl:
        key-alias: damian
        key-store: ${KEYSTORE_PKCS12_PATH}
        # key-store: classpath:keystore/damian.p12
        key-store-type: PKCS12
        key-store-password: ${KEYSTORE_PKCS12_PASSWORD} 

    port: 8005